### ISSUE TITLE
Embed sending not working

### ISSUE THREAD

**Issue by twinkbymotya** [rigwild/discord-self-bot-console#12]
Sending embeds doesn't work. Returns error 50006: "Cannot send an empty message". The sendEmbed function doesn't work too. If I try to send an embed with a message, only the message will be sent, and the embed will not be sent.
Here is the code I am using:
```js
await api.apiCall(`/channels/863292952545198090/messages`, {
    "embeds": [{
        "title": "Hello, Embed!",
        "description": "This is an embedded message."
    }]
}, 'POST')
```

**Comment by rigwild** [comment]
Just tried on my side. You are right the API changed to `{ embeds: Embed[] }` in the last API update.

Adding a content stops the error but the embed is not sent anyway

```js
await api.apiCall(`/channels/${cid}/messages`, {
  "content": "Hello, World!",
  "tts": false,
  "embeds": [{
    "title": "Hello, Embed!",
    "description": "This is an embedded message."
  }]
}, 'POST')
```

Maybe they removed the ability for non bot accounts to send embeds?

**Comment by twinkbymotya** [comment]
I don't quite understand if [this](https://discord.com/developers/docs/topics/oauth2#bot-vs-user-accounts) will help, but it says that bots have full access to the API, which means that selfbots have partial access.
Chances are you're right and they've removed the ability for non-bot accounts to send embeds.

**Comment by rigwild** [comment]
Yeah, I noticed previously that new features like components were not being sent too (https://github.com/rigwild/discord-self-bot-console/discussions/8#discussioncomment-1783198)

Ok, rip, this is not possible anymore... https://www.reddit.com/r/Discord_selfbots/comments/sa0hc2/discord_embeds_patched/
