### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by zodiaccong** [rigwild/discord-self-bot-console#44]
![image](https://user-images.githubusercontent.com/52649950/196913181-665fffbb-ff6d-4611-be81-861b58f32ab3.png)
Your code used to work fine for me, but it doesn't work today. Have you encountered this problem? Can you help me fix them? Thank you.

**Comment by DeadLyBro** [comment]
Can you send your code??

**Comment by zodiaccong** [comment]
Thank you, my problem is token. My token changed.

**Comment by DeadLyBro** [comment]
@zodiaccong You're right. I checked [http response codes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#http), 401 meaning Unauthorized; The `Authorization` header is missing or invalid.
